[phases.setup]
nixPkgs = ['nodejs_18', 'python39', 'pkg-config', 'libtool', 'autoconf', 'automake', 'gnumake', 'gcc']

[phases.install]
cmds = ['npm install --verbose']

[phases.build]
cmds = ['npm run build:prod']

[start]
cmd = 'node server/index.js'